# FILE SOURCE:   https://github.com/big-data-europe/docker-spark

version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8091:8091"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8092:8091"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: spark-history-server
      restart: always
      depends_on:
        - spark-master
      ports:
        - "18091:18091"
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events